import { Zain } from "next/font/google";
import "./globals.css";
import Header from "@/components/home/header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const zain = Zain({
  weight: ["200", "300", "400", "700"],
  subsets: ["arabic"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${zain.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
